#!/bin/bash

set -veuo pipefail

CONFIG="$(pwd)/config"

# Configure

sudo chsh -s /bin/bash spin

# Install packages

sudo apt-get remove -y neovim
sudo apt-get install -y vim

sudo apt-get install -y bash-completion
sudo apt-get install -y git-gui gitk

# Link config files

ln -sf "$CONFIG/bashrc" ~/.bashrc
ln -sf "$CONFIG/profile" ~/.profile
ln -sf "$CONFIG/gitconfig" ~/.gitconfig
ln -sf "$CONFIG/gitignore_global" ~/.gitignore_global
ln -sf "$CONFIG/vimrc" ~/.vimrc
ln -sf "$CONFIG/zlogin" ~/.zlogin

# Run install scripts

"$CONFIG/vim/install"
